#!/usr/bin/perl -w

use strict;
use Mojo::DOM;
use Getopt::Long;
&Getopt::Long::config('bundling');

my %STATUS_CODE = ('UNKNOWN' => '3', 'OK' => '0');

my ($opt_h, $url, $country_string);
GetOptions(
    "h|help" => \$opt_h,
    "u|url=s" => \$url,
    "c|country-string=s" => \$country_string,
);

if ($opt_h || !defined $url || !defined $country_string) {
    print_usage();
}

my $output = "UNKNOWN";
my ($total, $deaths, $cured) = (-1) x 3;

my $dom = Mojo::DOM->new;
$dom->parse(getResponse($url));
my $table = $dom->find('table#main_table_countries_today');
for my $row ($table->first->find('tr')->each) {
    next unless $row->find('td')->first;
    my $iter = 0;
    for my $el ($row->find('td')->each) {
        if ($iter == 1) {
            last unless $el->find('a')->first;
            last if $el->find('a')->first->content ne $country_string;
        }
        my $content = $el->content =~ s/,//gr =~ s/^\s+|\s+$//r;
        if ($iter == 2) {
            $total = $content;
        } elsif ($iter == 4) {
            $deaths = $content;
        } elsif ($iter == 6) {
            $cured = $content;
            last;
        }
        ++$iter;
        $output = 'OK';
    }
    last if $iter == 6;
}
print "$output: Stats|total=$total;;;;; deaths=$deaths;;;;; cured=$cured;;;;;";
exit($STATUS_CODE{$output});

sub getResponse {
    my $scrape_url = shift;
    my $query = "wget -qO - \'". $scrape_url . "\'";
    $query = `$query`;
}

sub print_usage {
    print <<EOF;

Usage: $0 -u <target-URL> -c <country-name>

Plugin scrapes target URL for corona stats.
Units are numbers of cases

    Options:
    -h, --help
    Get this help message
    -u, --url
    URL to query
    -c, --country-string
    Name of a country of interest. Must be exact contents of given table cell

EOF
    exit($STATUS_CODE{"UNKNOWN"});
}
